In [2]:
import numpy as np 

In [3]:
arr = np.array([[10,20,30,40,50]])
arr

array([[10, 20, 30, 40, 50]])

In [4]:
arr1=np.array([11,45,34,26,89,56])
arr2=np.array([2,3,4,5,7,2])


print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1//arr2)
print(arr1/arr2)
print(arr1**arr2)
print()
print()
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.median(arr1))
print(np.median(arr2))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))


[13 48 38 31 96 58]
[ 9 42 30 21 82 54]
[ 22 135 136 130 623 112]
[ 5 15  8  5 12 28]
[ 5.5        15.          8.5         5.2        12.71428571 28.        ]
[           121          91125        1336336       11881376
 44231334895529           3136]


150
30.0
30.0
39.5
3.5
10
50
14.142135623730951
200.0


In [5]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [6]:
age=np.array([
    [20,30,40,50,60],
    [60,80,46,32,12]
])
print(age)
print()

marks=np.array([
    [90,70],
    [23,45],
    [35,60],
    [85,95],
    [99,35],
])
print(marks)

[[20 30 40 50 60]
 [60 80 46 32 12]]

[[90 70]
 [23 45]
 [35 60]
 [85 95]
 [99 35]]


# indexing on 2d array


SYNTAX


VARIABLE_NAME[ROW_INDEX,COL_INDEX]

In [7]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [8]:
print(arr[0,1])
print(arr[1,2])
print(arr[2,0])
print(arr[0,2])
print(arr[1,1])
print(arr[-2,-2])

20
60
70
30
50
50


In [9]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# Slicing on 2d array 


arr[ROW_SLICE, COLUMN_SLICE]

Each slice follows: 

start : stop : step

In [10]:
print(arr[0:1,1:4])
print()
print(arr[0:1,1:3])
print()
print(arr[0:,1:])
print()
print(arr[0:3:2,0:])
print()
print(arr[::2,0:])
print()
print(arr[1:2,::2])
print()
print(arr[1:3,0:2])
print()
print(arr[0:,1:3])
print()
print(arr[::2,::2])


[[20 30]]

[[20 30]]

[[20 30]
 [50 60]
 [80 90]]

[[10 20 30]
 [70 80 90]]

[[10 20 30]
 [70 80 90]]

[[40 60]]

[[40 50]
 [70 80]]

[[20 30]
 [50 60]
 [80 90]]

[[10 30]
 [70 90]]


# array with constant operations



In [11]:
print(arr+20)
print(arr-3)
print(arr*99)
print(arr/4)
print(arr//4)
print(arr**2)


[[ 30  40  50]
 [ 60  70  80]
 [ 90 100 110]]
[[ 7 17 27]
 [37 47 57]
 [67 77 87]]
[[ 990 1980 2970]
 [3960 4950 5940]
 [6930 7920 8910]]
[[ 2.5  5.   7.5]
 [10.  12.5 15. ]
 [17.5 20.  22.5]]
[[ 2  5  7]
 [10 12 15]
 [17 20 22]]
[[ 100  400  900]
 [1600 2500 3600]
 [4900 6400 8100]]


# array with array operation on 2d array

In [12]:
arr1=np.array([
    [29,10,20,28],
    [27,59,31,45]
])
arr2=np.array([
    [16,12,55,24],
    [27,59,31,45]
])

In [13]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1//arr2)
print(arr1**arr2)

[[ 45  22  75  52]
 [ 54 118  62  90]]
[[ 13  -2 -35   4]
 [  0   0   0   0]]
[[ 464  120 1100  672]
 [ 729 3481  961 2025]]
[[1.8125     0.83333333 0.36363636 1.16666667]
 [1.         1.         1.         1.        ]]
[[1 0 0 1]
 [1 1 1 1]]
[[-2056423596428435135        1000000000000                    0
  -7763924282610024448]
 [-5278486589563110205  -145357957422043229 -4642015662142636065
   2604998672350111773]]


##  statistical operations on 2d array

In [14]:
arr1

array([[29, 10, 20, 28],
       [27, 59, 31, 45]])

In [15]:
print(np.sum(arr1))
print(np.mean(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.median(arr1))

249
31.125
10
59
28.5


# axis 

**axis=0 = down = column-wise**

**axis=1 = across = row-wise**

In [16]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# axis = 0 

In [17]:
print(np.sum(arr,axis=0))
print(np.mean(arr,axis=0))
print(np.min(arr,axis=0))
print(np.max(arr,axis=0))
print(np.median(arr,axis=0))

[120 150 180]
[40. 50. 60.]
[10 20 30]
[70 80 90]
[40. 50. 60.]


# axis=1

In [18]:
print(np.sum(arr,axis=1))
print(np.mean(arr,axis=1))
print(np.min(arr,axis=1))
print(np.max(arr,axis=1))
print(np.median(arr,axis=1))

[ 60 150 240]
[20. 50. 80.]
[10 40 70]
[30 60 90]
[20. 50. 80.]


# different ways to create numpy array

# 1. arange() 

arange = “Give me numbers with this gap.”


**np.arange(starting_value,ending_value,updation)**

In [19]:
arr1 = np.arange(1,10)
print(arr1)
arr2 = np.arange(100,110,2)
arr2

[1 2 3 4 5 6 7 8 9]


array([100, 102, 104, 106, 108])

In [20]:

print(np.arange(10,0,-1))
print(np.arange(1.5,3.0,0.5))
print(np.arange(-2.0,2.0,0.5))


[10  9  8  7  6  5  4  3  2  1]
[1.5 2.  2.5]
[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5]


# 2.linspace

linspace = “Give me this many equally spaced numbers

**np.linspace(startingvalue,endingvalue,no.ofvalues)**

In [21]:
print(np.linspace(1,4,15))
print(np.linspace(-1,1,6))

[1.         1.21428571 1.42857143 1.64285714 1.85714286 2.07142857
 2.28571429 2.5        2.71428571 2.92857143 3.14285714 3.35714286
 3.57142857 3.78571429 4.        ]
[-1.  -0.6 -0.2  0.2  0.6  1. ]


# 3.zeros()


**np.zeros(n)---->  1d array**

**np.zeros((row_size,col_size))----> 2d array**

In [22]:
print(np.zeros(5))
print(np.zeros(17))

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [23]:
print(np.zeros((2,2)))
print(np.zeros((5,3)))
print(np.zeros((4,5)))

[[0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 4.ones()

**np.zeros(n)---->  1d array**

**np.zeros((row_size,col_size))---->  2d array**

In [24]:
print(np.ones(5))
print(np.ones(17))

[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [25]:
print(np.ones((2,2)))
print(np.ones((5,3)))
print(np.ones((5,5)))

[[1. 1.]
 [1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# 5.identity()

**np.identity(n)** 

**diagonal 1s, remaining 0s**


In [26]:
print(np.identity(2))
print(np.identity(5))
print(np.identity(13))

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# 6.randint()

**generates random integer values within a specified range.**

**np.random.randint(sv,ev,no.ofvalues)   --->  1d**

**np.random.randint(sv,ev,(rowsize,columnsize)  --->  2d**

In [27]:
print(np.random.randint(1,10))  # single inegter    # generates one random number 
print(np.random.randint(1, 70, 1))  # array of single integer
print(np.random.randint(17, 20, 9)) # generates 9 random numbers with in the range 

5
[4]
[18 19 19 19 18 19 17 17 19]


In [28]:
print(np.random.randint(1,10,(4,5)))
print(np.random.randint(1,10,size=(4,5)))

[[7 3 5 4 4]
 [7 5 5 7 7]
 [6 2 7 6 1]
 [5 6 5 8 2]]
[[3 2 1 9 3]
 [4 7 9 9 9]
 [5 1 4 7 8]
 [2 8 7 2 6]]


# 7.rand

**np.random.rand(n)--->1d**

**np.random.rand(rowsize,colsize)  -->2d**

In [29]:
print(np.random.rand(10))
print()
print(np.random.rand(5,2))

[0.28494289 0.36254258 0.41980586 0.79127261 0.77935967 0.11193761
 0.38310178 0.79008622 0.45962718 0.85526936]

[[0.91948748 0.75014116]
 [0.39455375 0.86611715]
 [0.75733589 0.50612987]
 [0.19823439 0.06167982]
 [0.3703794  0.04361525]]


# 8.randn() 

**np.random.randn(n)   --->1d array**

**np.random.randn(rowsize,colsize)  --->2d**

In [30]:
print(np.random.randn(10))
print(np.random.randn(3))

[-1.27458471  0.4569462  -0.61317238 -0.27447552 -1.26496018 -0.2055752
  1.19751569  0.11432816 -0.30029857  0.61914607]
[ 0.86930932 -0.02068208  0.85577253]


In [31]:
print(np.random.randn(5,3))

[[ 0.64945987  0.76111411 -0.85669331]
 [ 1.48780066  1.19015337 -0.96709778]
 [ 0.33767975  1.32628197  0.62828045]
 [ 1.52549964  0.08608199 -0.49786881]
 [-0.89532817  0.72085046 -0.52186028]]


# converting list into an arr

# 9. array()


# converting list into an arr

**coll=[val1,val2....valn]**

**arr=np.array(coll)**




In [32]:
list1=[10,20,30,40,50]
arr=np.array(list1)
print(arr)

[10 20 30 40 50]


In [33]:
lis=[[20,30,40,50],[45,'viv',20,45]]
arr=np.array(lis)
print(arr)

[['20' '30' '40' '50']
 ['45' 'viv' '20' '45']]


In [34]:
tup=(20,30,40)
arr=np.array(tup)
print(arr)

[20 30 40]


In [35]:
k=(1,2,3,4,5,6)
c=np.array(k)
print(c)

[1 2 3 4 5 6]


# type coversion priority order

** When we create a NumPy array containing different data types , NumPy tries to make all elements have one common data type.**

In [36]:
arr=np.array([True,2,3,1])
print(arr)
print(arr.dtype)
#int has highest priority compare to bool

[1 2 3 1]
int64


In [37]:
arr=np.array([True,2,3.45,1.89,45,False])
print(arr)
print(arr.dtype)
#float has highest priority compare to bool and int

[ 1.    2.    3.45  1.89 45.    0.  ]
float64


In [38]:
import numpy as np
arr=np.array(['vijay',32,4.5,89,12,'yash'])
print(arr)
print(arr.dtype)
#string has highest priority except object

['vijay' '32' '4.5' '89' '12' 'yash']
<U32


In [39]:
arr=np.array([1,'hai',{1,2,3}])
print(arr)
#obect take container stores all values but it does not support list and tuple bcz dimensional problems
#object has highest priority compare to all
print(arr.dtype)

[1 'hai' {1, 2, 3}]
object


In [40]:
arr=np.array(['vijay',32,4.5,89,12,'yash'])
print(arr)
print(arr.dtype) #string
arr=np.array(['vijay',32,4.5,89,12,'yash'],dtype=object)
print(arr.dtype)
#string has highest priority except object

['vijay' '32' '4.5' '89' '12' 'yash']
<U32
object


In [43]:
print(arr)
arr.ndim

['vijay' 32 4.5 89 12 'yash']


1

# 10.ndim

**np.ndim(arr)**

**How many dimensions does this array have?**

In [44]:
arr1=np.array([1,2,3,4])
arr2=np.array([['apple','bananna','orange'],
              ['tomoto','onion','chilly']])
arr3=np.array([['apple','bananna','orange'],
              [5,3,6]])
print(np.ndim(arr1))
print(arr1.ndim)
print(np.ndim(arr2)) 
print(np.ndim(arr3))

1
1
2
2


# **11.shape()**

**np.shape(arr)**

**size of an array along each dimension**

**For a 2D array, it tells :(number of rows, number of columns)**

In [45]:
marks 

array([[90, 70],
       [23, 45],
       [35, 60],
       [85, 95],
       [99, 35]])

In [49]:
print(arr1)
arr2

[1 2 3 4]


array([['apple', 'bananna', 'orange'],
       ['tomoto', 'onion', 'chilly']], dtype='<U7')

In [47]:
print(np.shape(arr1))
print(np.shape(marks))
print(np.shape(arr2))

(4,)
(5, 2)
(2, 3)


**ndim ---->>>> tells how many dimensions** 

**shape ---->>>> tells the size of each dimension**

# **12.reshape()**  

   **changes the structure**

**np.reshape(arr,(row_size,col_size))**

**note:-no.of rows*no.of col=no.of ele in an array**

In [53]:
arr=np.array([4,5,6,7,10,20])
print(np.reshape(arr,(2,3)))

print(np.reshape(arr,(3,2)))
print(np.reshape(arr,(6,1)))
print(np.reshape(arr,(1,6)))


arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

new_arr = arr.reshape(3, 2)

print(new_arr)

[[ 4  5  6]
 [ 7 10 20]]
[[ 4  5]
 [ 6  7]
 [10 20]]
[[ 4]
 [ 5]
 [ 6]
 [ 7]
 [10]
 [20]]
[[ 4  5  6  7 10 20]]
[[10 20]
 [30 40]
 [50 60]]


**-1 tells NumPy:**
“You calculate this dimension automatically.”

**You provide one dimension (2), and NumPy calculates the other based on the number of elements.**



arr.reshape(2, -1)      # ✅

arr.reshape(-1, 2)      # ✅

arr.reshape(2, 3, -1)   # ✅

#  flatten()

**arr.flatten()**

In [51]:
marks 

array([[90, 70],
       [23, 45],
       [35, 60],
       [85, 95],
       [99, 35]])

In [52]:
marks.flatten()

array([90, 70, 23, 45, 35, 60, 85, 95, 99, 35])

# **4.size**

**arr.size**

In [54]:
arr=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(arr.size)

12


# **dtype**

**arr.dtype**

In [56]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
print(arr.dtype)

int64


# with out broadcasting

In [58]:
arr6=np.array([10,20,30])
arr7=np.array([1,2,3])
arr6+arr7

array([11, 22, 33])

# Scaler broadcasting

In [59]:
arr8=np.array([10,20,30])
num=5
arr8+num

array([15, 25, 35])

# broadcasting with array

In [63]:
marks=np.array([
    [70,80,90],
    [60,75,85],
    [88,92,95]
])
bonus=np.array([5,2,3])

bonus1=np.array([
    [5],
    [2],
    [3]
])

In [64]:
np.shape(bonus)

(3,)

# row broadcasting

In [65]:
marks+bonus

array([[75, 82, 93],
       [65, 77, 88],
       [93, 94, 98]])

# column broadcasting

In [67]:

bonus1=np.array([
    [5],
    [2],
    [3]
])

marks+bonus1

array([[75, 85, 95],
       [62, 77, 87],
       [91, 95, 98]])

# 3d Array

In [ ]:
import numpy as np
arr=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

# 2 layers
# × 2 rows
# × 3 columns

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# indexing

# arr[layer, row, column]

print(arr[0,1,1])
print(arr[1,0,2])


5
9


In [74]:
# slicing on 3d

# arr[layer_slice, row_slice, column_slice] 
print(arr)
print("============================")
print(arr[0,0:1,0:])
print("============================")
print(arr[1,0:,0:2])
print("============================")
print(arr[0:2,0:1,1:3])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]]
[[ 7  8]
 [10 11]]
[[[2 3]]

 [[8 9]]]
